version: "3.3"
services:
  backend:
    container_name: backend
    build: ./server
    ports:
      - "8000:8000"
  frontend:
    container_name: frontend
    build: .
    ports:
      - "3000:3000"

